import esbuild from "esbuild";
import { createRequire } from "node:module";
import process from "node:process";

const banner =
  "/* eslint-disable */\n" +
  "/* This file is generated by esbuild. */";

const prod = process.argv[2] === "production";
const require = createRequire(import.meta.url);

const aliasPlugin = {
  name: "alias-node-builtins",
  setup(build) {
    const aliases = {
      buffer: "buffer/",
      events: "events/",
      path: "path-browserify",
      process: "process/browser",
      stream: "stream-browserify",
      util: "util/",
    };

    for (const [from, to] of Object.entries(aliases)) {
      build.onResolve({ filter: new RegExp(`^${from}$`) }, () => ({ path: require.resolve(to) }));
    }
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view"],
  format: "cjs",
  inject: ["./esbuild.polyfills.mjs"],
  logLevel: "info",
  outfile: "main.js",
  platform: "browser",
  plugins: [aliasPlugin],
  sourcemap: prod ? false : "inline",
  target: "es2020",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
